# <b><span style='color:#0492fd'>|</span>Варіант 12</b>


## <b><span style='color:#F1C40F'>|</span> Задача 1</b>

Створити список N максимальних (Kmax) або мінімальних (Kmin) елементів колекції.

    N = [30, -10, 15, -5, 12, 20, 5, -14, 27, -1, 9, -20]
    
    Kmax = 3
    Kmin = 5

In [1]:
N = [30, -10, 15, -5, 12, 20, 5, -14, 27, -1, 9, -20]

Kmax = 3
Kmin = 5

Kmin_value = sorted(N)[:Kmin]
Kmax_value = sorted(N, reverse=True)[:Kmax]
print('Kmin = ', Kmin_value,'\nKmax = ', Kmax_value)

Kmin =  [-20, -14, -10, -5, -1] 
Kmax =  [30, 27, 20]


## <b><span style='color:#F1C40F'>|</span> Задача 2</b>

Об'єднати багато невеликих рядків в довгий рядок.

    'Весна', 'приходить', ',', 'птахи', 'повертаються', ',', 'квіти', 'розпускаються', '.'

In [2]:
list_of_words = 'Весна', 'приходить', ',', 'птахи', 'повертаються', ',', 'квіти', 'розпускаються', '.'

sentence = ' '.join(list_of_words)
print(sentence)

Весна приходить , птахи повертаються , квіти розпускаються .


## <b><span style='color:#F1C40F'>|</span> Задача 3</b>

Операції з матрицями:

    M = [[6, -4, 3], [2, 8, -5], [0, -7, 4]] 
    v = ([[1],[3],[-2]])

1. транспортувати M
2. M*MT=T
3. інфвертувати T
4. T*v(вектор)

In [3]:
import numpy as np

M = [[6, -4, 3], [2, 8, -5], [0, -7, 4]] 
v = ([[1],[3],[-2]])
print(M)

M_tr = np.transpose(M)
print('\n', 'M^T:', '\n', M_tr)

T = np.dot(M, M_tr)
print('\n', 'Multiple M * M^T:', '\n', T)

Inverted_T = np.linalg.inv(T)
print('\n', 'Inverted_T:', '\n', Inverted_T)

T_multiply_v = np.dot(Inverted_T, v)
print('\n', 'T_multiply_v:', '\n', T_multiply_v)

[[6, -4, 3], [2, 8, -5], [0, -7, 4]]

 M^T: 
 [[ 6  2  0]
 [-4  8 -7]
 [ 3 -5  4]]

 Multiple M * M^T: 
 [[ 61 -35  40]
 [-35  93 -76]
 [ 40 -76  65]]

 Inverted_T: 
 [[ 0.34311224 -0.97576531 -1.35204082]
 [-0.97576531  3.01658163  4.12755102]
 [-1.35204082  4.12755102  5.67346939]]

 T_multiply_v: 
 [[ 0.11989796]
 [-0.18112245]
 [-0.31632653]]


## <b><span style='color:#F1C40F'>|</span> Задача 4</b>

До дати (data) додайте d днів та виведіть

    data = 7/08/2021
    d = 300

In [4]:
from datetime import datetime
from datetime import timedelta

data = datetime(2021, 8, 7)  # рік, місяць, день
d = 300

result_data = data + timedelta(d)
print('start date:', data, '+', d, "d = ", result_data )

start date: 2021-08-07 00:00:00 + 300 d =  2022-06-03 00:00:00


## <b><span style='color:#F1C40F'>|</span> Задача 5</b>

Провести парсинг RSS-канала

    https://www.economist.com/latest/rss.xml

In [1]:
import feedparser
channel = feedparser.parse('https://www.economist.com/latest/rss.xml')

title = channel.feed.title
link = channel.feed.link
description = channel.feed.description

result = 'title: ' + title + '\n' + 'link: ' + link + '\n' + 'description: ' + description + '\n\n'
print(result)

print("\nItems: \n")
for item in channel.entries[:5]:
    string = "Item title: " + item.title + "\nItem link: " + item.link + "\nItem description: " + item.description + "\nPublished date: " + item.published + "\n\n"
    print(string)

title: Latest Updates
link: https://www.economist.com/latest/
description: The most recent blogs and online articles from The Economist



Items: 

Item title: Madridland
Item link: https://www.economist.com/podcasts/2024/09/21/madridland
Item description: How can Spain avoid the tourist trap?
Published date: Sat, 21 Sep 2024 09:00:00 +0000


Item title: Friedrich Merz, Germany’s chancellor-in-waiting?
Item link: https://www.economist.com/europe/2024/09/20/friedrich-merz-germanys-chancellor-in-waiting
Item description: He has strong odds of thrashing Olaf Scholz next year
Published date: Fri, 20 Sep 2024 20:04:11 +0000


Item title: What “supertall” skyscrapers reveal about countries that build them
Item link: https://www.economist.com/interactive/culture/2024/09/20/what-supertall-skyscrapers-reveal-about-countries-that-build-them
Item description: They are miracles of engineering and “boasts in glass and steel”
Published date: Fri, 20 Sep 2024 16:38:21 +0000


Item title: What happens